// Body-centroid detection from a person-segmentation mask PNG.
//
// AdjustOffsetDialog uses this to auto-detect horizontal alignment when
// the photo has a cached silhouette mask (iOS-only, generated by Vision via
// the PersonSegmentation Capacitor plugin). Falls back to face-detect-x in
// callers when no mask is available.
//
// The mask is an RGBA PNG where alpha = segmentation value (white = person,
// transparent = background). We walk the alpha channel, sum each pixel's
// alpha-weighted x position, then return the centroid as a CSS object-
// position x% (0-100).

const ALPHA_THRESHOLD = 64; // Ignore pixels below this alpha — soft mask edges.

/** Best-effort body-centroid x detection. Loads the mask PNG, computes the
 *  alpha-weighted average x of opaque pixels. Returns CSS object-position
 *  x% (0-100), or null when the mask can't be loaded / has no opaque pixels. */
export async function tryDetectBodyCenterX(maskUrl: string): Promise<number | null> {
  if (typeof window === 'undefined' || typeof document === 'undefined') return null;

  let bitmap: ImageBitmap | null = null;
  try {
    const res = await fetch(maskUrl);
    if (!res.ok) return null;
    const blob = await res.blob();
    bitmap = await createImageBitmap(blob);

    // Downsample for speed — full-res masks are 3024x4032; we don't need
    // every pixel for a centroid. 256px wide is enough precision.
    const targetW = 256;
    const scale = targetW / bitmap.width;
    const w = targetW;
    const h = Math.max(1, Math.round(bitmap.height * scale));

    const canvas = document.createElement('canvas');
    canvas.width = w;
    canvas.height = h;
    const ctx = canvas.getContext('2d');
    if (!ctx) return null;
    ctx.drawImage(bitmap, 0, 0, w, h);
    const data = ctx.getImageData(0, 0, w, h).data;

    let weightedSum = 0;
    let totalWeight = 0;
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const a = data[(y * w + x) * 4 + 3];
        if (a < ALPHA_THRESHOLD) continue;
        weightedSum += x * a;
        totalWeight += a;
      }
    }

    if (totalWeight === 0) return null;
    const centroidX = weightedSum / totalWeight;
    return Math.round((centroidX / w) * 1000) / 10;
  } catch {
    return null;
  } finally {
    bitmap?.close?.();
  }
}
