-- Migration 024: Exercise muscle audit — applied from AI-assisted audit pass.
--
-- Generated by scripts/generate-audit-migration.mjs from
--   ~/.gstack/projects/lewcart-Iron/exercise-muscle-audit-2026-05-01T06-29-49.csv
--
-- Each UPDATE keys on exercise UUID. The validate_exercise_muscles trigger
-- from migration 023 is the safety net — any non-canonical slug fails here.
-- Confidence: high + medium only. Low-confidence rows skipped (none in this
-- run, but the filter is in the generator).

BEGIN;

-- Ab Wheel [high] — primary: ∅ → core
UPDATE exercises SET primary_muscles = '["core"]'::jsonb WHERE uuid = 'f5c74593-13f3-4bf7-877a-223ccd9395c7';

-- Assisted Pull Up [high] — primary: ∅ → lats|biceps
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb WHERE uuid = '008993a3-8211-4e99-8c04-84fad453853a';

-- Banded Dead Bug [high] — secondary: core → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = 'a37d320d-c8df-4897-88ea-5939658c1f21';

-- Banded Glute Bridge (Warm-Up) [high] — secondary: hamstrings|hip_abductors → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = 'fd5ddc30-b1d8-4e55-878f-2cb0509e0281';

-- Banded Lateral Walk (Warm-Up) [high] — primary: glutes|hip_abductors → hip_abductors; secondary: ∅ → glutes
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb, secondary_muscles = '["glutes"]'::jsonb WHERE uuid = '26e6104c-1741-429d-8a2a-aca7d9134139';

-- Banded Lateral Walk (Warm-up) [high] — primary: glutes|hip_abductors → hip_abductors; secondary: ∅ → glutes
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb, secondary_muscles = '["glutes"]'::jsonb WHERE uuid = '9d66ac23-3e10-49ff-aca6-980b7b147fb0';

-- Bench Press: Barbell [high] — secondary: delts|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = 'c0d3c3cd-9f1f-4a89-b845-dab5923b22a7';

-- Bench Press: Barbell (Close Grip) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '7f521d26-66f9-40f5-b50a-044aac0803fe';

-- Bench Press: Barbell (Close Grip) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '7F521D26-66F9-40F5-B50A-044AAC0803FE';

-- Bench Press: Barbell (Decline) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = 'a7af0db8-c0b1-44ba-adb2-6c08e03cb2cc';

-- Bench Press: Barbell (Decline) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = 'A7AF0DB8-C0B1-44BA-ADB2-6C08E03CB2CC';

-- Bench Press: Barbell (Decline, Wide Grip) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '0E2E4708-35DC-4128-8B32-718FF68B5491';

-- Bench Press: Barbell (Decline, Wide Grip) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '0e2e4708-35dc-4128-8b32-718ff68b5491';

-- Bench Press: Barbell (Incline) [high] — primary: chest → chest|triceps; secondary: triceps → 
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'D2B09DAE-2E3B-4A7A-95F8-811E5E41B433';

-- Bench Press: Barbell (Incline) [high] — primary: chest → chest|triceps; secondary: triceps → 
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'd2b09dae-2e3b-4a7a-95f8-811e5e41b433';

-- Bench Press: Barbell (Reverse, Triceps) [high] — secondary: chest → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '8F2612C6-DC64-482C-A024-8EB103E8DF51';

-- Bench Press: Barbell (Reverse, Triceps) [high] — secondary: chest → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '8f2612c6-dc64-482c-a024-8eb103e8df51';

-- Bench Press: Barbell (Wide Grip) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '039D6D33-98FD-4CC7-A7AD-C96FAA0135AE';

-- Bench Press: Barbell (Wide Grip) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '039d6d33-98fd-4cc7-a7ad-c96faa0135ae';

-- Bench Press: Dumbbell [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '6b09e781-80c2-4116-ab82-c9fc31d49e43';

-- Bench Press: Dumbbell [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '6B09E781-80C2-4116-AB82-C9FC31D49E43';

-- Bench Press: Dumbbell (Decline) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = 'A541E362-0EAD-42DA-B109-D452312BA2CA';

-- Bench Press: Dumbbell (Decline) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = 'a541e362-0ead-42da-b109-d452312ba2ca';

-- Bench Press: Dumbbell (Incline) [high] — primary: chest → chest|triceps|delts; secondary: delts|triceps → 
UPDATE exercises SET primary_muscles = '["chest","triceps","delts"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'c04b1262-ef69-449e-963f-282d34a0aa8d';

-- Bench Press: Dumbbell (Incline) [high] — primary: chest → chest|triceps|delts; secondary: delts|triceps → 
UPDATE exercises SET primary_muscles = '["chest","triceps","delts"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'C04B1262-EF69-449E-963F-282D34A0AA8D';

-- Bench Press: Dumbbell (Incline, Hammer Grip) [high] — primary: chest → chest|triceps|delts; secondary: delts|triceps → 
UPDATE exercises SET primary_muscles = '["chest","triceps","delts"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '5999199f-0bc8-414a-96fd-fa3377afa5ef';

-- Bench Press: Dumbbell (Incline, Hammer Grip) [high] — primary: chest → chest|triceps|delts; secondary: delts|triceps → 
UPDATE exercises SET primary_muscles = '["chest","triceps","delts"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '5999199F-0BC8-414A-96FD-FA3377AFA5EF';

-- Bench Press: Machine [high] — secondary: delts|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = '74D42B22-1842-4B9F-B6A7-83B90472CB43';

-- Bench Press: Machine [high] — secondary: delts|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = '74d42b22-1842-4b9f-b6a7-83b90472cb43';

-- Bench Press: Machine (Decline) [high] — secondary: delts|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = '41ca09c9-e88c-42df-997e-7d6fea4a765e';

-- Bench Press: Machine (Decline) [high] — secondary: delts|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = '41CA09C9-E88C-42DF-997E-7D6FEA4A765E';

-- Bench Press: Smith Machine [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = 'aa58e724-d2bc-43bc-9af5-bed923ff67d9';

-- Bench Press: Smith Machine [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = 'AA58E724-D2BC-43BC-9AF5-BED923FF67D9';

-- Bench Press: Smith Machine (Close Grip) [high] — primary: triceps → triceps|chest; secondary: chest → 
UPDATE exercises SET primary_muscles = '["triceps","chest"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'e420336a-82da-4eb8-b821-9f29bb1a8d28';

-- Bench Press: Smith Machine (Close Grip) [high] — primary: triceps → triceps|chest; secondary: chest → 
UPDATE exercises SET primary_muscles = '["triceps","chest"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'E420336A-82DA-4EB8-B821-9F29BB1A8D28';

-- Bench Press: Smith Machine (Incline) [high] — primary: chest → chest|delts|triceps; secondary: delts|triceps → 
UPDATE exercises SET primary_muscles = '["chest","delts","triceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'A367C0FE-49B8-484A-B296-6D5EB723E0B2';

-- Bench Press: Smith Machine (Incline) [high] — primary: chest → chest|delts|triceps; secondary: delts|triceps → 
UPDATE exercises SET primary_muscles = '["chest","delts","triceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'a367c0fe-49b8-484a-b296-6d5eb723e0b2';

-- Biceps Curl: Cable [high] — secondary: delts|forearms → forearms
UPDATE exercises SET secondary_muscles = '["forearms"]'::jsonb WHERE uuid = 'EEBD10DB-1C6D-44CE-BB9A-EBC981CF95EB';

-- Biceps Curl: Cable [high] — secondary: delts|forearms → forearms
UPDATE exercises SET secondary_muscles = '["forearms"]'::jsonb WHERE uuid = 'eebd10db-1c6d-44ce-bb9a-ebc981cf95eb';

-- Biceps Curl: EZ Curl Bar [high] — secondary: delts|forearms → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '405E1A53-1383-4DF9-9368-86E3CCF38012';

-- Biceps Curl: EZ Curl Bar [high] — secondary: delts|forearms → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '405e1a53-1383-4df9-9368-86e3ccf38012';

-- Cable Hip Abduction [high] — primary: glutes|hip_abductors → hip_abductors; secondary: ∅ → glutes
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb, secondary_muscles = '["glutes"]'::jsonb WHERE uuid = '79a09a58-b93a-4846-afbd-a5ede04025a6';

-- Cable Hip Abduction [high] — primary: glutes|hip_abductors → hip_abductors; secondary: core|hip_abductors → glutes
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb, secondary_muscles = '["glutes"]'::jsonb WHERE uuid = '00cf869f-181c-4fe8-bd4b-4fc1fe267f47';

-- Cable Hip Abduction [high] — primary: glutes|hip_abductors → hip_abductors; secondary: ∅ → glutes
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb, secondary_muscles = '["glutes"]'::jsonb WHERE uuid = '5aea1c07-c852-45f8-bcdb-802618751e66';

-- Cable Hip Adduction [high] — primary: quads → hip_adductors; secondary: hip_adductors → quads
UPDATE exercises SET primary_muscles = '["hip_adductors"]'::jsonb, secondary_muscles = '["quads"]'::jsonb WHERE uuid = '52977031-70A7-4E08-98A1-4871B614B9FB';

-- Cable Hip Adduction [high] — primary: quads → hip_adductors; secondary: hip_adductors → quads
UPDATE exercises SET primary_muscles = '["hip_adductors"]'::jsonb, secondary_muscles = '["quads"]'::jsonb WHERE uuid = '52977031-70a7-4e08-98a1-4871b614b9fb';

-- Cable Kickback [high] — secondary: hamstrings → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '18b6ef69-dbf8-4ee9-8f3c-a878a1f5b733';

-- Cable Pull-Through [high] — primary: ∅ → glutes|hamstrings
UPDATE exercises SET primary_muscles = '["glutes","hamstrings"]'::jsonb WHERE uuid = '1b23eabf-d8ce-4ad8-98a8-66fbaa382a63';

-- Chest Press (Machine) [high] — primary: ∅ → chest
UPDATE exercises SET primary_muscles = '["chest"]'::jsonb WHERE uuid = 'e411b64d-2ffc-44ad-9705-250087a506c8';

-- Chin Tuck [medium] — primary: ∅ → core
UPDATE exercises SET primary_muscles = '["core"]'::jsonb WHERE uuid = '750bddfa-5df8-40dd-a09c-26533be753a6';

-- Chin Up (Narrow Parallel Grip) [medium] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '3B1EE73B-7ADA-40EA-96E7-2228883D9FD8';

-- Chin Up (Narrow Parallel Grip) [medium] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '3b1ee73b-7ada-40ea-96e7-2228883d9fd8';

-- Clamshell (Warm-Up) [high] — primary: glutes|hip_abductors → hip_abductors; secondary: ∅ → glutes
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb, secondary_muscles = '["glutes"]'::jsonb WHERE uuid = 'c806a82e-cffe-4199-843d-627e9f96d64d';

-- Clamshell (Warm-up) [high] — primary: glutes|hip_abductors → hip_abductors; secondary: ∅ → glutes
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb, secondary_muscles = '["glutes"]'::jsonb WHERE uuid = '174b3c17-f474-4c6f-804b-b152d1cb42ee';

-- Concentration Curl: Dumbbell [high] — secondary: forearms → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '1c61f93b-5e6b-4517-9378-2f250ea6d28f';

-- Concentration Curl: Dumbbell [high] — secondary: forearms → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '1C61F93B-5E6B-4517-9378-2F250EA6D28F';

-- Crunch (Machine) [high] — primary: ∅ → core
UPDATE exercises SET primary_muscles = '["core"]'::jsonb WHERE uuid = '2ce40e6b-5df8-4bd3-8267-1f1d5f09de08';

-- Dead bug [high] — primary: ∅ → core
UPDATE exercises SET primary_muscles = '["core"]'::jsonb WHERE uuid = '8439e6b1-6c02-4e69-bdd8-6250252161af';

-- Deadlift: Barbell [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = 'E301F9A9-9516-47E3-9E77-D2C7E50B4D7A';

-- Deadlift: Barbell [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = 'e301f9a9-9516-47e3-9e77-d2c7e50b4d7a';

-- Deadlift: Dumbbell [high] — primary: erectors → erectors|hamstrings; secondary: calves|hamstrings → calves
UPDATE exercises SET primary_muscles = '["erectors","hamstrings"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = '7b27c3c2-b4c0-423e-8472-90dafa53b5fb';

-- Deadlift: Dumbbell [high] — primary: erectors → erectors|hamstrings; secondary: calves|hamstrings → calves
UPDATE exercises SET primary_muscles = '["erectors","hamstrings"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = '7B27C3C2-B4C0-423E-8472-90DAFA53B5FB';

-- Deadlift: Smith Machine [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '734f6cd7-9787-45bf-91b2-eb61a9c05575';

-- Deadlift: Smith Machine [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '734F6CD7-9787-45BF-91B2-EB61A9C05575';

-- Dips (Chest) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = 'ac43fddc-d3c7-438d-a925-d4ef0f3ce290';

-- Dips (Chest) [high] — primary: chest → chest|triceps; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = 'AC43FDDC-D3C7-438D-A925-D4EF0F3CE290';

-- Dips (Triceps) [high] — secondary: chest|delts → chest
UPDATE exercises SET secondary_muscles = '["chest"]'::jsonb WHERE uuid = '971C7298-186F-4D2E-A79C-E4E3CC30277F';

-- Dips (Triceps) [high] — secondary: chest|delts → chest
UPDATE exercises SET secondary_muscles = '["chest"]'::jsonb WHERE uuid = '971c7298-186f-4d2e-a79c-e4e3cc30277f';

-- Dips: Machine [high] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '51c45857-f388-4538-a542-7703edd5d7a4';

-- Dips: Machine [high] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '51C45857-F388-4538-A542-7703EDD5D7A4';

-- Donkey Calf [high] — primary: ∅ → calves
UPDATE exercises SET primary_muscles = '["calves"]'::jsonb WHERE uuid = '7c9d246b-eeb3-4361-b3d3-1e64f842cdda';

-- Dumbbell Bulgarian Split Squat [high] — primary: glutes|hamstrings → glutes|quads; secondary: core|quads → hamstrings|core
UPDATE exercises SET primary_muscles = '["glutes","quads"]'::jsonb, secondary_muscles = '["hamstrings","core"]'::jsonb WHERE uuid = 'f71b92ea-00a1-4485-86d7-2394d03006d4';

-- Dumbbell Bulgarian Split Squat [high] — primary: glutes|hamstrings → glutes|quads; secondary: core|quads → hamstrings|core
UPDATE exercises SET primary_muscles = '["glutes","quads"]'::jsonb, secondary_muscles = '["hamstrings","core"]'::jsonb WHERE uuid = '6c757467-7fe8-419a-95d6-e660e480fbd7';

-- Dumbbell Overhead Press (Standing) [high] — secondary: core|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = 'aba9590d-0ed8-41f3-bb54-49cbe12b0e9d';

-- Dumbbell Overhead Press (Standing) [high] — secondary: core|mid_traps|triceps → triceps|core
UPDATE exercises SET secondary_muscles = '["triceps","core"]'::jsonb WHERE uuid = 'd6eba26f-b3b4-4c07-a13a-e82dba1dfacf';

-- Dumbbell Row (Single Arm) [medium] — primary: lats|rhomboids → lats; secondary: biceps|delts → rhomboids|biceps|delts
UPDATE exercises SET primary_muscles = '["lats"]'::jsonb, secondary_muscles = '["rhomboids","biceps","delts"]'::jsonb WHERE uuid = 'b96523e3-98c6-4ea5-8b91-174fec14050c';

-- Dumbbell Row (Single Arm) [medium] — primary: lats|rhomboids → lats; secondary: biceps|core|delts → rhomboids|biceps|core|delts
UPDATE exercises SET primary_muscles = '["lats"]'::jsonb, secondary_muscles = '["rhomboids","biceps","core","delts"]'::jsonb WHERE uuid = '5f2da054-e433-49b9-8f9d-0465af16b86d';

-- Dumbbell Step-Up [high] — primary: glutes|hamstrings → glutes|quads; secondary: quads → hamstrings
UPDATE exercises SET primary_muscles = '["glutes","quads"]'::jsonb, secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '1a9a9e60-5ab4-447f-9a8b-ce6599224892';

-- Dumbbell Step-Up [high] — primary: glutes|hamstrings → glutes|quads; secondary: core|quads → hamstrings|core
UPDATE exercises SET primary_muscles = '["glutes","quads"]'::jsonb, secondary_muscles = '["hamstrings","core"]'::jsonb WHERE uuid = 'd7f50484-1c53-4ecd-b499-19340de2cb84';

-- Dumbbell Y-Raise [high] — primary: delts|lower_traps → delts; secondary: rhomboids → rotator_cuff
UPDATE exercises SET primary_muscles = '["delts"]'::jsonb, secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '1324ab9a-305c-483a-921a-59344ef42900';

-- Dumbbell Y-Raise [high] — primary: delts|lower_traps → delts; secondary: rhomboids|rotator_cuff → rotator_cuff
UPDATE exercises SET primary_muscles = '["delts"]'::jsonb, secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '257f77ba-cf5f-49fa-88e8-509883059d13';

-- External Cable Rotation (Band) [high] — primary: ∅ → rotator_cuff
UPDATE exercises SET primary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '7fc29993-58c2-46c0-bef1-fd5e5b9a4c1b';

-- Face Pulls [high] — secondary: ∅ → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = 'C4035736-EAF3-4DAD-8B74-BD1537E6B72D';

-- Face Pulls [high] — secondary: ∅ → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = 'c4035736-eaf3-4dad-8b74-bd1537e6b72d';

-- Flutter Kicks [high] — primary: hamstrings → core; secondary: quads → quads|hamstrings
UPDATE exercises SET primary_muscles = '["core"]'::jsonb, secondary_muscles = '["quads","hamstrings"]'::jsonb WHERE uuid = '62B9751E-0E1B-4F91-926F-A0A599096DDE';

-- Flutter Kicks [high] — primary: hamstrings → core; secondary: quads → quads|hamstrings
UPDATE exercises SET primary_muscles = '["core"]'::jsonb, secondary_muscles = '["quads","hamstrings"]'::jsonb WHERE uuid = '62b9751e-0e1b-4f91-926f-a0a599096dde';

-- Flyes: Cable (Incline) [high] — secondary: biceps|forearms|triceps → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '721F71AE-879A-4F6A-87DB-09C7A6906D60';

-- Flyes: Cable (Incline) [high] — secondary: biceps|forearms|triceps → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '721f71ae-879a-4f6a-87db-09c7a6906d60';

-- Flyes: Dumbbell [high] — secondary: delts|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = 'C28FA94C-D311-450F-B208-6366A2992837';

-- Flyes: Dumbbell [high] — secondary: delts|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = 'c28fa94c-d311-450f-b208-6366a2992837';

-- Flyes: Dumbbell (Incline) [high] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '635746F0-1E44-4DAA-B2FA-81D1933F3EB3';

-- Flyes: Dumbbell (Incline) [high] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '635746f0-1e44-4daa-b2fa-81d1933f3eb3';

-- Front Raise and Pullover [medium] — primary: chest → chest|delts; secondary: delts|triceps → triceps
UPDATE exercises SET primary_muscles = '["chest","delts"]'::jsonb, secondary_muscles = '["triceps"]'::jsonb WHERE uuid = '670f794d-3d03-4dc9-ac69-68d06cb784d4';

-- Front Raise and Pullover [medium] — primary: chest → chest|delts; secondary: delts|triceps → triceps
UPDATE exercises SET primary_muscles = '["chest","delts"]'::jsonb, secondary_muscles = '["triceps"]'::jsonb WHERE uuid = '670F794D-3D03-4DC9-AC69-68D06CB784D4';

-- Front Raises: Barbell [medium] — secondary: chest|forearms → forearms
UPDATE exercises SET secondary_muscles = '["forearms"]'::jsonb WHERE uuid = 'd00de650-3fa1-4a3e-87f7-e512820eb2fe';

-- Front Raises: Barbell [medium] — secondary: chest|forearms → forearms
UPDATE exercises SET secondary_muscles = '["forearms"]'::jsonb WHERE uuid = 'D00DE650-3FA1-4A3E-87F7-E512820EB2FE';

-- Front Raises: Cable [medium] — secondary: chest|forearms → forearms
UPDATE exercises SET secondary_muscles = '["forearms"]'::jsonb WHERE uuid = '5cf92ab3-67f6-444c-a9b3-d4812b6cb06e';

-- Front Raises: Cable [medium] — secondary: chest|forearms → forearms
UPDATE exercises SET secondary_muscles = '["forearms"]'::jsonb WHERE uuid = '5CF92AB3-67F6-444C-A9B3-D4812B6CB06E';

-- Front Raises: Dumbbell [high] — secondary: ∅ → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '9c3417e1-2b6f-4e2d-9f49-0bf256ccc88d';

-- Front Raises: Dumbbell [high] — secondary: ∅ → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '9C3417E1-2B6F-4E2D-9F49-0BF256CCC88D';

-- Front Squat: Barbell [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '0ee3033b-5e17-4f16-b8c4-85569f0c1c14';

-- Front Squat: Barbell [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '0EE3033B-5E17-4F16-B8C4-85569F0C1C14';

-- GHD Hip Extension [high] — primary: ∅ → erectors
UPDATE exercises SET primary_muscles = '["erectors"]'::jsonb WHERE uuid = '55b6a549-6140-4184-acc1-c35d7f884e77';

-- Glute Cable Kick Back [high] — primary: ∅ → glutes
UPDATE exercises SET primary_muscles = '["glutes"]'::jsonb WHERE uuid = '3f0e3ac6-ca52-4ab5-9c34-be860355cff7';

-- Hack Squat: Machine (Narrow Stance) [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '2C0880E2-B58A-4178-B6E3-0B4E1455726C';

-- Hack Squat: Machine (Narrow Stance) [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '2c0880e2-b58a-4178-b6e3-0b4e1455726c';

-- Hip Abduction (Machine) [high] — primary: ∅ → hip_abductors
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb WHERE uuid = '8bbd4cf1-0bbc-43de-a7f9-73885d425d50';

-- Hip Thrust (Barbell) [high] — primary: ∅ → glutes; secondary: ∅ → hamstrings
UPDATE exercises SET primary_muscles = '["glutes"]'::jsonb, secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '6bcc12aa-4435-429c-aa81-f27a6c996e8d';

-- Hip Thrust (Barbell) — Banded Pulse [high] — primary: glutes|hip_abductors → glutes; secondary: core|hamstrings → hip_abductors|core|hamstrings
UPDATE exercises SET primary_muscles = '["glutes"]'::jsonb, secondary_muscles = '["hip_abductors","core","hamstrings"]'::jsonb WHERE uuid = 'ce29d312-1713-4299-9d95-55a6e91d2452';

-- Hyperextensions [high] — secondary: core|hamstrings → core
UPDATE exercises SET secondary_muscles = '["core"]'::jsonb WHERE uuid = 'DEB57677-680C-442E-AA95-7162C6126B18';

-- Hyperextensions [high] — secondary: core|hamstrings → core
UPDATE exercises SET secondary_muscles = '["core"]'::jsonb WHERE uuid = 'deb57677-680c-442e-aa95-7162c6126b18';

-- Incline Bench Shoulder Press (Dumbbell) [high] — primary: ∅ → delts|triceps
UPDATE exercises SET primary_muscles = '["delts","triceps"]'::jsonb WHERE uuid = '11efbe8d-8159-40d1-936e-4b3854a69336';

-- Internal Cable Rotation [medium] — secondary: biceps → biceps|rotator_cuff
UPDATE exercises SET secondary_muscles = '["biceps","rotator_cuff"]'::jsonb WHERE uuid = 'B346DE7B-2E5C-4509-83AF-B5E58BA065E1';

-- Internal Cable Rotation [medium] — primary: delts → delts|biceps; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["delts","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'b346de7b-2e5c-4509-83af-b5e58ba065e1';

-- Internal Cable Rotation (Band) [high] — primary: ∅ → rotator_cuff
UPDATE exercises SET primary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '0185f0ba-50ef-41d5-90ef-5c599436bb53';

-- Inverted Row [medium] — primary: lats → lats|chest|mid_traps; secondary: biceps|chest → biceps
UPDATE exercises SET primary_muscles = '["lats","chest","mid_traps"]'::jsonb, secondary_muscles = '["biceps"]'::jsonb WHERE uuid = '7e117b7f-114f-415e-a646-780d9c744ed2';

-- Inverted Row [medium] — primary: lats → lats|chest|mid_traps; secondary: biceps|chest → biceps
UPDATE exercises SET primary_muscles = '["lats","chest","mid_traps"]'::jsonb, secondary_muscles = '["biceps"]'::jsonb WHERE uuid = '7E117B7F-114F-415E-A646-780D9C744ED2';

-- Lateral Raise: Cable (Bent Over) [high] — secondary: lats|mid_traps → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '6c214811-961a-408a-8aba-365f4f35a7fd';

-- Lateral Raise: Cable (Bent Over) [medium] — secondary: lats|mid_traps → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '6C214811-961A-408A-8ABA-365F4F35A7FD';

-- Lateral Raise: Dumbbell [medium] — secondary: forearms → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '92D5B230-A226-45DD-8AA1-D3271EC24AF8';

-- Lateral Raise: Dumbbell [medium] — secondary: forearms → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '92d5b230-a226-45dd-8aa1-d3271ec24af8';

-- Leg Press [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '8b3de466-1552-4978-a378-55f64e8ca66b';

-- Leg Press [high] — primary: quads → quads|hamstrings; secondary: calves|hamstrings → calves
UPDATE exercises SET primary_muscles = '["quads","hamstrings"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = '8B3DE466-1552-4978-A378-55F64E8CA66B';

-- Leg Press (Narrow Stance) [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '5dc1047e-aff0-4717-b9bd-6225b1d39af5';

-- Leg Press (Narrow Stance) [high] — secondary: calves|hamstrings → hamstrings
UPDATE exercises SET secondary_muscles = '["hamstrings"]'::jsonb WHERE uuid = '5DC1047E-AFF0-4717-B9BD-6225B1D39AF5';

-- Leg Press (Single Leg) [high] — primary: ∅ → quads|hamstrings|glutes
UPDATE exercises SET primary_muscles = '["quads","hamstrings","glutes"]'::jsonb WHERE uuid = 'fd8f5a1b-ed37-4afe-b9af-c2f7c0b1e812';

-- Lunges: Barbell [high] — primary: hamstrings → quads|hamstrings|glutes; secondary: calves|glutes|quads → calves
UPDATE exercises SET primary_muscles = '["quads","hamstrings","glutes"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = 'D645140E-5761-4096-AD31-8E66A8D6A562';

-- Lunges: Barbell [high] — primary: hamstrings → quads|hamstrings|glutes; secondary: calves|glutes|quads → calves
UPDATE exercises SET primary_muscles = '["quads","hamstrings","glutes"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = 'd645140e-5761-4096-ad31-8e66a8d6a562';

-- Lunges: Dumbbell [high] — primary: hamstrings → hamstrings|glutes|quads; secondary: calves|glutes|quads → calves
UPDATE exercises SET primary_muscles = '["hamstrings","glutes","quads"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = 'd3be22c1-9276-4ef9-9888-2e98d76dc618';

-- Lunges: Dumbbell [high] — primary: hamstrings → hamstrings|glutes|quads; secondary: calves|glutes|quads → calves
UPDATE exercises SET primary_muscles = '["hamstrings","glutes","quads"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = 'D3BE22C1-9276-4EF9-9888-2E98D76DC618';

-- Lunges: Dumbbell (Walking) [high] — primary: hamstrings → quads|glutes|hamstrings; secondary: calves|glutes|quads → calves
UPDATE exercises SET primary_muscles = '["quads","glutes","hamstrings"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = 'e8763784-ddcf-4a7b-9321-189c1e93a1b7';

-- Lunges: Dumbbell (Walking) [high] — primary: hamstrings → quads|glutes|hamstrings; secondary: calves|glutes|quads → calves
UPDATE exercises SET primary_muscles = '["quads","glutes","hamstrings"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = 'E8763784-DDCF-4A7B-9321-189C1E93A1B7';

-- Overhead Press: Barbell [high] — primary: delts → delts|triceps; secondary: triceps → 
UPDATE exercises SET primary_muscles = '["delts","triceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '3D405857-F1A8-4F85-858C-231F0CEF653A';

-- Overhead Press: Barbell [high] — primary: delts → delts|triceps; secondary: triceps → 
UPDATE exercises SET primary_muscles = '["delts","triceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '3d405857-f1a8-4f85-858c-231f0cef653a';

-- Pallof Rotations (Band) [high] — primary: ∅ → core
UPDATE exercises SET primary_muscles = '["core"]'::jsonb WHERE uuid = '522886b6-9b59-4254-8389-d481489d3184';

-- Pull Up [high] — primary: lats → lats|biceps; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '59185216-6167-4427-ac10-38a3fda17572';

-- Pull Up [high] — primary: lats → lats|biceps; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '59185216-6167-4427-AC10-38A3FDA17572';

-- Pulldown (Underhand) [high] — primary: lats → lats|biceps; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'a7e6cae5-2000-4e57-8704-d6b867a57439';

-- Pulldown (Underhand) [high] — primary: lats → lats|biceps; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'A7E6CAE5-2000-4E57-8704-D6B867A57439';

-- Pulldown (Wide Grip) [high] — primary: lats → lats|biceps; secondary: biceps|lats → 
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '91f466ba-1d91-459a-8c5b-81e0b46c54ac';

-- Pulldown (Wide Grip) [high] — primary: lats → lats|biceps; secondary: biceps|lats → 
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '91F466BA-1D91-459A-8C5B-81E0B46C54AC';

-- Pulldown: V Bar  [high] — primary: lats → lats|biceps; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'FD99103C-B691-4DD3-A40A-8CCEF23FBEC5';

-- Pulldown: V Bar  [high] — primary: lats → lats|biceps; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = 'fd99103c-b691-4dd3-a40a-8ccef23fbec5';

-- Push Up [high] — primary: chest → chest|triceps|biceps; secondary: delts|triceps → core
UPDATE exercises SET primary_muscles = '["chest","triceps","biceps"]'::jsonb, secondary_muscles = '["core"]'::jsonb WHERE uuid = '77C531EB-3CAD-4773-9F18-1A230B1FF7E5';

-- Push Up [high] — primary: chest → chest|triceps|core; secondary: delts|triceps → delts
UPDATE exercises SET primary_muscles = '["chest","triceps","core"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '77c531eb-3cad-4773-9f18-1a230b1ff7e5';

-- Rear Delt Fly (Machine) [high] — primary: ∅ → delts; secondary: ∅ → rotator_cuff
UPDATE exercises SET primary_muscles = '["delts"]'::jsonb, secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = 'f3c22c57-c84d-4725-a3bd-1e1d036727cc';

-- Rear Delt Fly Bentover (Dumbbell) [high] — primary: ∅ → delts|rotator_cuff
UPDATE exercises SET primary_muscles = '["delts","rotator_cuff"]'::jsonb WHERE uuid = 'bef4fb1e-92f6-402f-9d7a-5ee0c014b081';

-- Rear Deltoid Raise (Bent Over) [high] — secondary: ∅ → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '95A2FF8B-332D-427A-9EBD-7CE3151D5F4A';

-- Rear Deltoid Raise (Bent Over) [high] — secondary: ∅ → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '95a2ff8b-332d-427a-9ebd-7ce3151d5f4a';

-- Rear Deltoid Raise (Lying) [high] — secondary: ∅ → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = 'e905ce43-2692-44c4-8e98-6657caeaa3d4';

-- Rear Deltoid Raise (Lying) [high] — secondary: ∅ → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = 'E905CE43-2692-44C4-8E98-6657CAEAA3D4';

-- Rear Deltoid Row: Barbell [high] — secondary: biceps → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = 'd39c7398-c0db-4501-95a3-67e8b27c7921';

-- Rear Deltoid Row: Barbell [high] — secondary: biceps → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = 'D39C7398-C0DB-4501-95A3-67E8B27C7921';

-- Rear Deltoid Row: Smith Machine [high] — secondary: biceps → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '0926F2D0-B09A-4D74-9EDF-3654D79A4CDF';

-- Rear Deltoid Row: Smith Machine [high] — primary: delts → delts|rotator_cuff; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["delts","rotator_cuff"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '0926f2d0-b09a-4d74-9edf-3654d79a4cdf';

-- Reverse Flyes: Cable [high] — secondary: lats|triceps → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '19D4F31D-AA33-4013-83DF-342DD6305AD5';

-- Reverse Flyes: Cable [high] — secondary: lats|triceps → rotator_cuff
UPDATE exercises SET secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '19d4f31d-aa33-4013-83df-342dd6305ad5';

-- Romanian Deadlift [high] — primary: hamstrings → hamstrings|glutes|quads; secondary: calves|glutes|quads → calves
UPDATE exercises SET primary_muscles = '["hamstrings","glutes","quads"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = '37DF9EB1-8E5F-404E-91B2-36210D356F95';

-- Romanian Deadlift [high] — primary: hamstrings → hamstrings|glutes|quads; secondary: calves|glutes|quads → calves
UPDATE exercises SET primary_muscles = '["hamstrings","glutes","quads"]'::jsonb, secondary_muscles = '["calves"]'::jsonb WHERE uuid = '37df9eb1-8e5f-404e-91b2-36210d356f95';

-- Romanian Deadlift (Dumbbell) [high] — primary: glutes|hamstrings → glutes|hamstrings|erectors; secondary: erectors → 
UPDATE exercises SET primary_muscles = '["glutes","hamstrings","erectors"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '49fb8c33-7c3f-4b19-b4ca-45958ec1725c';

-- Romanian Deadlift (Dumbbell) [high] — primary: glutes|hamstrings → glutes|hamstrings|erectors; secondary: core|erectors → core
UPDATE exercises SET primary_muscles = '["glutes","hamstrings","erectors"]'::jsonb, secondary_muscles = '["core"]'::jsonb WHERE uuid = 'c200adc6-3b52-4be2-bc4d-c9c69722e879';

-- Romanian Deadlift: Dumbbell [high] — secondary: core|erectors|forearms → erectors
UPDATE exercises SET secondary_muscles = '["erectors"]'::jsonb WHERE uuid = 'a310d3f2-f7e5-47f8-97ab-77aca7d33c6e';

-- Row (Machine, Chest-Supported) [high] — primary: ∅ → lats|rhomboids|mid_traps
UPDATE exercises SET primary_muscles = '["lats","rhomboids","mid_traps"]'::jsonb WHERE uuid = '5fac1455-db81-4eaf-bc69-13458a74315f';

-- Row: Barbell (Bent Over) [high] — primary: lats → lats|mid_traps
UPDATE exercises SET primary_muscles = '["lats","mid_traps"]'::jsonb WHERE uuid = '6EB5B9C9-C953-459E-AFDE-2D31B1BEFAE0';

-- Row: Barbell (Bent Over) [high] — primary: lats → lats|mid_traps
UPDATE exercises SET primary_muscles = '["lats","mid_traps"]'::jsonb WHERE uuid = '6eb5b9c9-c953-459e-afde-2d31b1befae0';

-- Row: Barbell (Bent Over, Reverse) [medium] — primary: lats → lats|mid_traps|biceps; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["lats","mid_traps","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '794f1bdb-9f8c-487e-866d-d6e54e28a522';

-- Row: Barbell (Bent Over, Reverse) [medium] — primary: lats → lats|mid_traps|biceps; secondary: biceps → 
UPDATE exercises SET primary_muscles = '["lats","mid_traps","biceps"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '794F1BDB-9F8C-487E-866D-D6E54E28A522';

-- Row: Cable (Seated) [high] — primary: lats → lats|biceps; secondary: biceps|erectors → erectors
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '["erectors"]'::jsonb WHERE uuid = 'C30BC020-CD01-4DC6-BACD-BAB8C88D208F';

-- Row: Cable (Seated) [high] — primary: lats → lats|biceps; secondary: biceps|erectors → erectors
UPDATE exercises SET primary_muscles = '["lats","biceps"]'::jsonb, secondary_muscles = '["erectors"]'::jsonb WHERE uuid = 'c30bc020-cd01-4dc6-bacd-bab8c88d208f';

-- Row: Dumbbell (One Arm) [high] — primary: lats → lats|delts; secondary: biceps|delts → biceps
UPDATE exercises SET primary_muscles = '["lats","delts"]'::jsonb, secondary_muscles = '["biceps"]'::jsonb WHERE uuid = '1C18115B-4985-4CAE-BA7E-FBD86827C6FF';

-- Row: Dumbbell (One Arm) [high] — primary: lats → lats|delts; secondary: biceps|delts → biceps
UPDATE exercises SET primary_muscles = '["lats","delts"]'::jsonb, secondary_muscles = '["biceps"]'::jsonb WHERE uuid = '1c18115b-4985-4cae-ba7e-fbd86827c6ff';

-- Row: T-Bar [high] — primary: lats → lats|mid_traps|biceps; secondary: biceps|delts → delts
UPDATE exercises SET primary_muscles = '["lats","mid_traps","biceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '44694efa-7d2e-4c7f-ab7d-dc4f66cafb60';

-- Row: T-Bar [high] — primary: lats → lats|mid_traps|biceps; secondary: biceps|delts → delts
UPDATE exercises SET primary_muscles = '["lats","mid_traps","biceps"]'::jsonb, secondary_muscles = '["delts"]'::jsonb WHERE uuid = '44694EFA-7D2E-4C7F-AB7D-DC4F66CAFB60';

-- Seated Cable Row (Low Row) [high] — primary: ∅ → lats|rhomboids|mid_traps
UPDATE exercises SET primary_muscles = '["lats","rhomboids","mid_traps"]'::jsonb WHERE uuid = '4ad58032-467f-4df6-b01d-27460a67d151';

-- Short Lever Copenhagen [high] — primary: core|hip_adductors → hip_adductors; secondary: core|glutes → glutes
UPDATE exercises SET primary_muscles = '["hip_adductors"]'::jsonb, secondary_muscles = '["glutes"]'::jsonb WHERE uuid = '661bee70-89f0-416a-b90e-5a87abd353b0';

-- Shoulder Press: Dumbbell [high] — secondary: chest|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = '2e087495-346b-4824-96bb-9cd854029e87';

-- Shoulder Press: Dumbbell [high] — secondary: chest|triceps → triceps
UPDATE exercises SET secondary_muscles = '["triceps"]'::jsonb WHERE uuid = '2E087495-346B-4824-96BB-9CD854029E87';

-- Shrugs: Cable [high] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = 'BDD44C1A-EDC3-48AE-89BC-DE1CB540BBFD';

-- Shrugs: Cable [high] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = 'bdd44c1a-edc3-48ae-89bc-de1cb540bbfd';

-- Shrugs: Smith Machine [high] — primary: delts → mid_traps
UPDATE exercises SET primary_muscles = '["mid_traps"]'::jsonb WHERE uuid = '9A268413-B96A-4943-94BC-C36FC0C91E07';

-- Shrugs: Smith Machine [high] — primary: delts → mid_traps
UPDATE exercises SET primary_muscles = '["mid_traps"]'::jsonb WHERE uuid = '9a268413-b96a-4943-94bc-c36fc0c91e07';

-- Single Leg RDL [high] — secondary: core|hip_abductors → core
UPDATE exercises SET secondary_muscles = '["core"]'::jsonb WHERE uuid = '0abfaa02-154c-4e4d-8046-cf46c3ecd6b3';

-- Skull Crusher [high] — secondary: chest → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '7210f17f-91f7-401f-89cf-271332113319';

-- Skull Crusher [high] — secondary: chest → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '7210F17F-91F7-401F-89CF-271332113319';

-- Skull Crusher (Decline, Close Grip) [high] — secondary: chest → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '1b9acd34-b41b-48c1-a28e-f576484d8944';

-- Skull Crusher (Decline, Close Grip) [high] — secondary: chest → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '1B9ACD34-B41B-48C1-A28E-F576484D8944';

-- Squat: Barbell [high] — primary: quads → quads|hamstrings; secondary: hamstrings → 
UPDATE exercises SET primary_muscles = '["quads","hamstrings"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '2339f5bd-2e8c-4446-b1a5-6156b1192229';

-- Squat: Barbell [high] — primary: quads → quads|hamstrings; secondary: hamstrings → 
UPDATE exercises SET primary_muscles = '["quads","hamstrings"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '2339F5BD-2E8C-4446-B1A5-6156B1192229';

-- Squat: Barbell (Narrow Stance) [high] — secondary: calves|glutes|hamstrings → glutes|hamstrings
UPDATE exercises SET secondary_muscles = '["glutes","hamstrings"]'::jsonb WHERE uuid = '9ed2222b-7af0-493f-abae-181deb8a167a';

-- Squat: Barbell (Narrow Stance) [high] — secondary: calves|glutes|hamstrings → glutes|hamstrings
UPDATE exercises SET secondary_muscles = '["glutes","hamstrings"]'::jsonb WHERE uuid = '9ED2222B-7AF0-493F-ABAE-181DEB8A167A';

-- Squat: Barbell (Wide Stance) [high] — primary: quads → quads|hip_adductors
UPDATE exercises SET primary_muscles = '["quads","hip_adductors"]'::jsonb WHERE uuid = '3B587709-4111-495D-BC4C-0658BCEE4145';

-- Squat: Barbell (Wide Stance) [high] — primary: quads → quads|hip_adductors
UPDATE exercises SET primary_muscles = '["quads","hip_adductors"]'::jsonb WHERE uuid = '3b587709-4111-495d-bc4c-0658bcee4145';

-- Squat: Dumbbell [high] — secondary: calves|hamstrings → hamstrings|glutes
UPDATE exercises SET secondary_muscles = '["hamstrings","glutes"]'::jsonb WHERE uuid = 'B7ACD3EA-57FE-437F-9286-A03A3C58AAD7';

-- Squat: Smith Machine [high] — secondary: calves|glutes|hamstrings → glutes|hamstrings
UPDATE exercises SET secondary_muscles = '["glutes","hamstrings"]'::jsonb WHERE uuid = '9D96C412-5D6C-4FDD-9781-1B89AF31EE3D';

-- Squat: Smith Machine [high] — secondary: calves|glutes|hamstrings → glutes|hamstrings
UPDATE exercises SET secondary_muscles = '["glutes","hamstrings"]'::jsonb WHERE uuid = '9d96c412-5d6c-4fdd-9781-1b89af31ee3d';

-- Thigh Abductor [high] — primary: quads → hip_abductors; secondary: hamstrings → 
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '3DBA09C5-B563-412D-B5DA-ECF33C131986';

-- Thigh Abductor [high] — primary: quads → hip_abductors; secondary: hamstrings → 
UPDATE exercises SET primary_muscles = '["hip_abductors"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '3dba09c5-b563-412d-b5da-ecf33c131986';

-- Thigh Adductor [high] — primary: quads → hip_adductors; secondary: hamstrings → 
UPDATE exercises SET primary_muscles = '["hip_adductors"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '989BDD5D-1186-4634-A95E-E9BD3DE6C01A';

-- Thigh Adductor [high] — primary: quads → hip_adductors; secondary: hamstrings → 
UPDATE exercises SET primary_muscles = '["hip_adductors"]'::jsonb, secondary_muscles = '[]'::jsonb WHERE uuid = '989bdd5d-1186-4634-a95e-e9bd3de6c01a';

-- Triceps Extension: Dumbbell (Incline) [high] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '36E7BDFE-64BB-4A9B-BEA2-A80B3144F0B5';

-- Triceps Extension: Dumbbell (Incline) [high] — secondary: delts → 
UPDATE exercises SET secondary_muscles = '[]'::jsonb WHERE uuid = '36e7bdfe-64bb-4a9b-bea2-a80b3144f0b5';

-- Wall Slide [high] — primary: ∅ → delts; secondary: ∅ → rotator_cuff
UPDATE exercises SET primary_muscles = '["delts"]'::jsonb, secondary_muscles = '["rotator_cuff"]'::jsonb WHERE uuid = '3ee2a560-d5e3-4d21-bbab-a8c380ecfb95';

-- Post-flight: verify every exercise still has non-empty primary_muscles
-- (defense in depth — generator filters this above too).
DO $$
DECLARE empty_count INT;
BEGIN
  SELECT COUNT(*) INTO empty_count FROM exercises WHERE primary_muscles = '[]'::jsonb;
  IF empty_count > 0 THEN
    RAISE WARNING 'Migration 024: % exercise(s) still have empty primary_muscles after audit. Re-run audit with --slug to retry, or hand-tag.', empty_count;
  END IF;
END $$;

COMMIT;
