import { NextRequest, NextResponse } from 'next/server';
import { put } from '@vercel/blob';
import { requireApiKey } from '@/lib/api-auth';
import { updateProgressPhoto } from '@/db/queries';

export const runtime = 'nodejs';

const MAX_MASK_BYTES = 5 * 1024 * 1024;

/** POST /api/progress-photos/[uuid]/mask
 *
 * Multipart upload of a person-segmentation mask PNG generated by the iOS
 * Vision plugin (see `src/lib/silhouette.ts`). Stores in Vercel Blob, sets
 * `mask_url` on the row. Server-owned cache: clients never need to PATCH
 * this column directly.
 *
 * Request:  multipart/form-data with `file` field (PNG, ≤5MB)
 * Response: { mask_url: string }
 */
export async function POST(request: NextRequest, ctx: { params: Promise<{ uuid: string }> }) {
  const denied = requireApiKey(request);
  if (denied) return denied;

  const { uuid } = await ctx.params;

  const formData = await request.formData();
  const file = formData.get('file') as File | null;
  if (!file) return NextResponse.json({ error: 'file is required' }, { status: 400 });
  if (file.type && file.type !== 'image/png') {
    return NextResponse.json({ error: 'mask must be image/png' }, { status: 400 });
  }
  if (file.size > MAX_MASK_BYTES) {
    return NextResponse.json({ error: `mask exceeds ${MAX_MASK_BYTES} bytes` }, { status: 413 });
  }

  // Random suffix in path so the URL isn't trivially guessable from the
  // photo uuid alone — silhouettes are body-shape outlines, treat them
  // with the same privacy posture as the source JPEG.
  const blob = await put(`progress-photos/masks/${uuid}-${crypto.randomUUID()}.png`, file, {
    access: 'public',
    contentType: 'image/png',
  });

  const updated = await updateProgressPhoto(uuid, { mask_url: blob.url });
  if (!updated) return NextResponse.json({ error: 'photo not found' }, { status: 404 });

  return NextResponse.json({ mask_url: blob.url });
}
