'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Play } from 'lucide-react';
import { openYouTube, parseYouTubeUrl } from '@/lib/youtube-url';

// Iron-style demo strip: up to 3 portrait cells in a row. When there are
// 3 demo frames (legacy bundled catalog), all cells are frames. When
// there are 1 or 2 demo frames (the AI-generated pair flow), the leading
// cell is a free `leadingSlot` (caller passes a compact PB readout) so
// the strip keeps a consistent 3-up rhythm without dead air. The
// remaining cells cycle through the available frames at ~1Hz.
//
// Image source priority:
//   1. exercise.image_urls (Vercel Blob, AI-generated in-app)
//   2. /exercise-images/{uuid}/0{N}.jpg (bundled in public/, build-time
//      sourced from everkinetic-data + AI-generated by the dev script)
//
// Cycle: setInterval at 1000ms swaps the highlighted frame. All frames
// render simultaneously in a horizontal strip (so the user sees the
// full motion at once) AND the active one gets a subtle ring + scale
// emphasis, which is what makes the loop "read" as a single movement.
//
// Failure modes:
//   - 02.jpg 404s → per-frame onError hides only that frame; cycle
//     continues with surviving frames. Does NOT mutate image_count
//     locally (synced source-of-truth must not flip on transient
//     network errors).
//   - All frames fail → strip hides itself entirely.
//   - youtube_url null → strip is non-interactive (just animates).
//   - youtube_url set + tap → openYouTube routes to YouTube app/Safari.

interface Props {
  exerciseUuid: string;
  imageCount: number;
  imageUrls: string[] | null;
  youtubeUrl: string | null;
  /** Smaller variant for the in-workout modal — capped width, less
   *  visual real estate. Defaults to false (full-width on the detail page). */
  compact?: boolean;
  /** Optional content for the leading cell (left third). Rendered when
   *  there are fewer than 3 frame sources, so the strip keeps a 3-up
   *  rhythm with PB / metadata in the empty slot. Ignored when there
   *  are 3 frames (legacy bundled catalog) — frames take priority. */
  leadingSlot?: ReactNode;
}

const TICK_MS = 1000;

export function ExerciseDemoStrip({
  exerciseUuid,
  imageCount,
  imageUrls,
  youtubeUrl,
  compact = false,
  leadingSlot,
}: Props) {
  // Frame source resolution — image_urls (Blob) wins; otherwise bundled.
  const sources = useMemo(() => {
    if (Array.isArray(imageUrls) && imageUrls.length > 0) return imageUrls;
    if (imageCount <= 0) return [] as string[];
    const n = Math.min(Math.max(imageCount, 1), 3);
    return Array.from({ length: n }, (_, i) =>
      `/exercise-images/${exerciseUuid}/${String(i + 1).padStart(2, '0')}.jpg`
    );
  }, [exerciseUuid, imageCount, imageUrls]);

  // Per-frame loaded state. Once a frame errors, it stays hidden until
  // exercise changes. We don't mutate image_count — that's synced truth.
  const [hidden, setHidden] = useState<Set<number>>(() => new Set());
  const [activeIdx, setActiveIdx] = useState(0);

  // Reset hidden set when sources change (different exercise)
  useEffect(() => {
    setHidden(new Set());
    setActiveIdx(0);
  }, [exerciseUuid]);

  // Cycle the highlighted frame. Skips hidden frames; if all hidden,
  // the interval still ticks but renders nothing visible.
  useEffect(() => {
    if (sources.length <= 1) return; // nothing to cycle
    const id = setInterval(() => {
      setActiveIdx(prev => {
        for (let off = 1; off <= sources.length; off++) {
          const next = (prev + off) % sources.length;
          if (!hidden.has(next)) return next;
        }
        return prev;
      });
    }, TICK_MS);
    return () => clearInterval(id);
  }, [sources.length, hidden]);

  if (sources.length === 0 || hidden.size >= sources.length) return null;

  // Show the leading PB/meta slot only when there's room (frame count < 3).
  // With 3 bundled frames the strip fills all cells; the slot would push
  // a frame off, which we don't want.
  const showLeadingSlot = leadingSlot != null && sources.length < 3;

  const yt = parseYouTubeUrl(youtubeUrl);
  const interactive = yt != null;

  const onTap = () => {
    if (interactive) openYouTube(youtubeUrl);
  };

  const ariaLabel = interactive
    ? `Exercise demonstration; tap to open YouTube reference`
    : `Exercise demonstration`;

  return (
    <div
      className={`relative ${compact ? 'max-w-md mx-auto' : 'w-full'}`}
      role={interactive ? 'button' : 'group'}
      aria-label={ariaLabel}
      onClick={onTap}
      onKeyDown={interactive ? (e) => { if (e.key === 'Enter') onTap(); } : undefined}
      tabIndex={interactive ? 0 : -1}
    >
      <div className="grid grid-cols-3 gap-1.5 bg-card border border-border rounded-2xl p-2">
        {showLeadingSlot && (
          <div className="aspect-[3/4] rounded-lg overflow-hidden">
            {leadingSlot}
          </div>
        )}
        {sources.map((src, i) => {
          if (hidden.has(i)) return <div key={i} className="aspect-[3/4] bg-muted/40 rounded-lg" />;
          const isActive = i === activeIdx;
          return (
            <div
              key={`${src}-${i}`}
              className={`aspect-[3/4] overflow-hidden rounded-lg transition-all duration-300 ${
                isActive
                  ? 'ring-2 ring-primary scale-[1.02] shadow-md'
                  : 'opacity-60 scale-[0.98]'
              }`}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={src}
                alt={`Frame ${i + 1}`}
                className="w-full h-full object-cover"
                loading="lazy"
                onError={() => setHidden(prev => new Set(prev).add(i))}
              />
            </div>
          );
        })}
      </div>
      {interactive && (
        <div className="absolute top-3 right-3 bg-black/50 text-white rounded-full p-1.5 pointer-events-none">
          <Play className="h-3.5 w-3.5" fill="currentColor" />
        </div>
      )}
    </div>
  );
}
