// Generated by scripts/gen-healthkit-types.mjs from src/lib/healthkit-types.json.
// DO NOT EDIT MANUALLY. Edit the JSON and run `npm run gen:healthkit`.
// CI drift test verifies this file matches the JSON on every PR.

import Foundation
import HealthKit

enum HealthKitTypes {

    /// All read + write types we request from HealthKit, bundled for requestAuthorization.
    /// Types gated by iOS version are skipped on older OS via @available.
    /// Types gated by a UserDefaults feature flag are skipped when the flag is false.
    static func allRequestedTypes() -> (read: Set<HKObjectType>, write: Set<HKSampleType>) {
        var read: Set<HKObjectType> = []
        var write: Set<HKSampleType> = []

        // Steps (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .stepCount) {
            read.insert(_t)
        }

        // Active Energy (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .activeEnergyBurned) {
            read.insert(_t)
            write.insert(_t)
        }

        // Basal Energy (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .basalEnergyBurned) {
            read.insert(_t)
        }

        // Exercise Minutes (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .appleExerciseTime) {
            read.insert(_t)
        }

        // Stand Time (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .appleStandTime) {
            read.insert(_t)
        }

        // Stand Hours (category, read)
        if let _t = HKCategoryType.categoryType(forIdentifier: .appleStandHour) {
            read.insert(_t)
        }

        // Walking Heart Rate (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .walkingHeartRateAverage) {
            read.insert(_t)
        }

        // Walking Speed (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .walkingSpeed) {
            read.insert(_t)
        }

        // Walking + Running Distance (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .distanceWalkingRunning) {
            read.insert(_t)
        }

        // Heart Rate (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .heartRate) {
            read.insert(_t)
        }

        // HRV (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .heartRateVariabilitySDNN) {
            read.insert(_t)
        }

        // Resting Heart Rate (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .restingHeartRate) {
            read.insert(_t)
        }

        // VO2 Max (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .vo2Max) {
            read.insert(_t)
        }

        // HR Recovery (1 min) (quantity, read, iOS 16.0+)
        if #available(iOS 16.0, *) {
            if let _t = HKQuantityType.quantityType(forIdentifier: .heartRateRecoveryOneMinute) {
                read.insert(_t)
            }
        }

        // Blood Pressure (Systolic) (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .bloodPressureSystolic) {
            read.insert(_t)
            write.insert(_t)
        }

        // Blood Pressure (Diastolic) (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .bloodPressureDiastolic) {
            read.insert(_t)
            write.insert(_t)
        }

        // Blood Oxygen (SpO2) (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .oxygenSaturation) {
            read.insert(_t)
        }

        // Body Temperature (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .bodyTemperature) {
            read.insert(_t)
            write.insert(_t)
        }

        // Sleeping Wrist Temperature (quantity, read, iOS 17.0+)
        if #available(iOS 17.0, *) {
            if let _t = HKQuantityType.quantityType(forIdentifier: .appleSleepingWristTemperature) {
                read.insert(_t)
            }
        }

        // Respiratory Rate (quantity, read)
        if let _t = HKQuantityType.quantityType(forIdentifier: .respiratoryRate) {
            read.insert(_t)
        }

        // Blood Glucose (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .bloodGlucose) {
            read.insert(_t)
            write.insert(_t)
        }

        // Body Mass (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .bodyMass) {
            read.insert(_t)
            write.insert(_t)
        }

        // Body Fat % (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .bodyFatPercentage) {
            read.insert(_t)
            write.insert(_t)
        }

        // Lean Mass (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .leanBodyMass) {
            read.insert(_t)
            write.insert(_t)
        }

        // BMI (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .bodyMassIndex) {
            read.insert(_t)
            write.insert(_t)
        }

        // Waist Circumference (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .waistCircumference) {
            read.insert(_t)
            write.insert(_t)
        }

        // Height (quantity, readWrite)
        if let _t = HKQuantityType.quantityType(forIdentifier: .height) {
            read.insert(_t)
            write.insert(_t)
        }

        // Workouts (workout, readWrite)
        read.insert(HKObjectType.workoutType())
        write.insert(HKObjectType.workoutType())

        // Workout Routes (GPS) (workoutRoute, write)
        write.insert(HKSeriesType.workoutRoute())

        // Sleep (category, read)
        if let _t = HKCategoryType.categoryType(forIdentifier: .sleepAnalysis) {
            read.insert(_t)
        }

        // Mindful Minutes (category, readWrite)
        if let _t = HKCategoryType.categoryType(forIdentifier: .mindfulSession) {
            read.insert(_t)
            write.insert(_t)
        }

        // Dietary Energy (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryEnergyConsumed) {
            write.insert(_t)
        }

        // Protein (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryProtein) {
            write.insert(_t)
        }

        // Carbohydrates (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryCarbohydrates) {
            write.insert(_t)
        }

        // Total Fat (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFatTotal) {
            write.insert(_t)
        }

        // Saturated Fat (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFatSaturated) {
            write.insert(_t)
        }

        // Monounsaturated Fat (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFatMonounsaturated) {
            write.insert(_t)
        }

        // Polyunsaturated Fat (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFatPolyunsaturated) {
            write.insert(_t)
        }

        // Fiber (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFiber) {
            write.insert(_t)
        }

        // Sugar (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietarySugar) {
            write.insert(_t)
        }

        // Sodium (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietarySodium) {
            write.insert(_t)
        }

        // Caffeine (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryCaffeine) {
            write.insert(_t)
        }

        // Cholesterol (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryCholesterol) {
            write.insert(_t)
        }

        // Water (quantity, write)
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryWater) {
            write.insert(_t)
        }

        // Medications (medicationDoseEvent, read, iOS 26.0+, flag: rebirth.medications.enabled)
        if #available(iOS 26.0, *) {
            if UserDefaults.standard.bool(forKey: "rebirth.medications.enabled") {
            }
        }

        return (read, write)
    }

    /// Sample-type list for deletion sweeps. Includes only writable types.
    static func allWritableTypesForDelete() -> [HKSampleType] {
        var types: [HKSampleType] = []
        if let _t = HKQuantityType.quantityType(forIdentifier: .activeEnergyBurned) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .bloodPressureSystolic) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .bloodPressureDiastolic) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .bodyTemperature) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .bloodGlucose) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .bodyMass) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .bodyFatPercentage) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .leanBodyMass) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .bodyMassIndex) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .waistCircumference) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .height) { types.append(_t) }
        types.append(HKObjectType.workoutType())
        types.append(HKSeriesType.workoutRoute())
        if let _t = HKCategoryType.categoryType(forIdentifier: .mindfulSession) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryEnergyConsumed) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryProtein) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryCarbohydrates) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFatTotal) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFatSaturated) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFatMonounsaturated) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFatPolyunsaturated) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryFiber) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietarySugar) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietarySodium) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryCaffeine) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryCholesterol) { types.append(_t) }
        if let _t = HKQuantityType.quantityType(forIdentifier: .dietaryWater) { types.append(_t) }
        return types
    }

    /// All tsKeys, in the same order as the JSON catalog. Used by checkPermissionStatus
    /// to populate the status map and by the TS UI to render rows.
    static let allTsKeys: [String] = [
        "stepCount",
        "activeEnergyBurned",
        "basalEnergyBurned",
        "appleExerciseTime",
        "appleStandTime",
        "appleStandHour",
        "walkingHeartRateAverage",
        "walkingSpeed",
        "distanceWalkingRunning",
        "heartRate",
        "heartRateVariabilitySDNN",
        "restingHeartRate",
        "vo2Max",
        "heartRateRecoveryOneMinute",
        "bloodPressureSystolic",
        "bloodPressureDiastolic",
        "oxygenSaturation",
        "bodyTemperature",
        "appleSleepingWristTemperature",
        "respiratoryRate",
        "bloodGlucose",
        "bodyMass",
        "bodyFatPercentage",
        "leanBodyMass",
        "bodyMassIndex",
        "waistCircumference",
        "height",
        "workout",
        "workoutRoute",
        "sleepAnalysis",
        "mindfulSession",
        "dietaryEnergyConsumed",
        "dietaryProtein",
        "dietaryCarbohydrates",
        "dietaryFatTotal",
        "dietaryFatSaturated",
        "dietaryFatMonounsaturated",
        "dietaryFatPolyunsaturated",
        "dietaryFiber",
        "dietarySugar",
        "dietarySodium",
        "dietaryCaffeine",
        "dietaryCholesterol",
        "dietaryWater",
        "medicationDoseEvent",
    ]

    /// tsKeys that map to write types. checkPermissionStatus can return real auth status
    /// for these (iOS hides read auth status by design).
    static let writeTsKeys: Set<String> = [
        "activeEnergyBurned",
        "bloodPressureSystolic",
        "bloodPressureDiastolic",
        "bodyTemperature",
        "bloodGlucose",
        "bodyMass",
        "bodyFatPercentage",
        "leanBodyMass",
        "bodyMassIndex",
        "waistCircumference",
        "height",
        "workout",
        "workoutRoute",
        "mindfulSession",
        "dietaryEnergyConsumed",
        "dietaryProtein",
        "dietaryCarbohydrates",
        "dietaryFatTotal",
        "dietaryFatSaturated",
        "dietaryFatMonounsaturated",
        "dietaryFatPolyunsaturated",
        "dietaryFiber",
        "dietarySugar",
        "dietarySodium",
        "dietaryCaffeine",
        "dietaryCholesterol",
        "dietaryWater",
    ]

    /// Resolve a tsKey to its HKObjectType for authorization-status queries.
    /// Returns nil if the type is unavailable on this iOS version, gated off by a
    /// feature flag, or unrecognized. Mirrors the gating logic in allRequestedTypes()
    /// so no caller can accidentally bypass either check.
    static func objectType(forTsKey key: String) -> HKObjectType? {
        switch key {
        case "stepCount":
            return HKQuantityType.quantityType(forIdentifier: .stepCount)
        case "activeEnergyBurned":
            return HKQuantityType.quantityType(forIdentifier: .activeEnergyBurned)
        case "basalEnergyBurned":
            return HKQuantityType.quantityType(forIdentifier: .basalEnergyBurned)
        case "appleExerciseTime":
            return HKQuantityType.quantityType(forIdentifier: .appleExerciseTime)
        case "appleStandTime":
            return HKQuantityType.quantityType(forIdentifier: .appleStandTime)
        case "appleStandHour":
            return HKCategoryType.categoryType(forIdentifier: .appleStandHour)
        case "walkingHeartRateAverage":
            return HKQuantityType.quantityType(forIdentifier: .walkingHeartRateAverage)
        case "walkingSpeed":
            return HKQuantityType.quantityType(forIdentifier: .walkingSpeed)
        case "distanceWalkingRunning":
            return HKQuantityType.quantityType(forIdentifier: .distanceWalkingRunning)
        case "heartRate":
            return HKQuantityType.quantityType(forIdentifier: .heartRate)
        case "heartRateVariabilitySDNN":
            return HKQuantityType.quantityType(forIdentifier: .heartRateVariabilitySDNN)
        case "restingHeartRate":
            return HKQuantityType.quantityType(forIdentifier: .restingHeartRate)
        case "vo2Max":
            return HKQuantityType.quantityType(forIdentifier: .vo2Max)
        case "heartRateRecoveryOneMinute":
            if #available(iOS 16.0, *) {
                return HKQuantityType.quantityType(forIdentifier: .heartRateRecoveryOneMinute)
            }
            return nil
        case "bloodPressureSystolic":
            return HKQuantityType.quantityType(forIdentifier: .bloodPressureSystolic)
        case "bloodPressureDiastolic":
            return HKQuantityType.quantityType(forIdentifier: .bloodPressureDiastolic)
        case "oxygenSaturation":
            return HKQuantityType.quantityType(forIdentifier: .oxygenSaturation)
        case "bodyTemperature":
            return HKQuantityType.quantityType(forIdentifier: .bodyTemperature)
        case "appleSleepingWristTemperature":
            if #available(iOS 17.0, *) {
                return HKQuantityType.quantityType(forIdentifier: .appleSleepingWristTemperature)
            }
            return nil
        case "respiratoryRate":
            return HKQuantityType.quantityType(forIdentifier: .respiratoryRate)
        case "bloodGlucose":
            return HKQuantityType.quantityType(forIdentifier: .bloodGlucose)
        case "bodyMass":
            return HKQuantityType.quantityType(forIdentifier: .bodyMass)
        case "bodyFatPercentage":
            return HKQuantityType.quantityType(forIdentifier: .bodyFatPercentage)
        case "leanBodyMass":
            return HKQuantityType.quantityType(forIdentifier: .leanBodyMass)
        case "bodyMassIndex":
            return HKQuantityType.quantityType(forIdentifier: .bodyMassIndex)
        case "waistCircumference":
            return HKQuantityType.quantityType(forIdentifier: .waistCircumference)
        case "height":
            return HKQuantityType.quantityType(forIdentifier: .height)
        case "workout":
            return HKObjectType.workoutType()
        case "workoutRoute":
            return HKSeriesType.workoutRoute()
        case "sleepAnalysis":
            return HKCategoryType.categoryType(forIdentifier: .sleepAnalysis)
        case "mindfulSession":
            return HKCategoryType.categoryType(forIdentifier: .mindfulSession)
        case "dietaryEnergyConsumed":
            return HKQuantityType.quantityType(forIdentifier: .dietaryEnergyConsumed)
        case "dietaryProtein":
            return HKQuantityType.quantityType(forIdentifier: .dietaryProtein)
        case "dietaryCarbohydrates":
            return HKQuantityType.quantityType(forIdentifier: .dietaryCarbohydrates)
        case "dietaryFatTotal":
            return HKQuantityType.quantityType(forIdentifier: .dietaryFatTotal)
        case "dietaryFatSaturated":
            return HKQuantityType.quantityType(forIdentifier: .dietaryFatSaturated)
        case "dietaryFatMonounsaturated":
            return HKQuantityType.quantityType(forIdentifier: .dietaryFatMonounsaturated)
        case "dietaryFatPolyunsaturated":
            return HKQuantityType.quantityType(forIdentifier: .dietaryFatPolyunsaturated)
        case "dietaryFiber":
            return HKQuantityType.quantityType(forIdentifier: .dietaryFiber)
        case "dietarySugar":
            return HKQuantityType.quantityType(forIdentifier: .dietarySugar)
        case "dietarySodium":
            return HKQuantityType.quantityType(forIdentifier: .dietarySodium)
        case "dietaryCaffeine":
            return HKQuantityType.quantityType(forIdentifier: .dietaryCaffeine)
        case "dietaryCholesterol":
            return HKQuantityType.quantityType(forIdentifier: .dietaryCholesterol)
        case "dietaryWater":
            return HKQuantityType.quantityType(forIdentifier: .dietaryWater)
        case "medicationDoseEvent":
            if #available(iOS 26.0, *) {
                if UserDefaults.standard.bool(forKey: "rebirth.medications.enabled") {
                    return nil
                }
            }
            return nil
        default: return nil
        }
    }
}
